// Mock data mirroring the Learnix ERP/CRM backend models (Prisma schema).
// Replace these with real API calls to your NestJS backend when wiring up.

export const ROLES = {
    SUPERADMIN: "Superadmin",
    ADMIN: "Admin",
    TEACHER: "Teacher",
    STUDENT: "Student",
};

export const stats = {
    totalStudents: 1284,
    totalTeachers: 64,
    activeGroups: 38,
    totalCourses: 22,
    monthlyRevenue: 184320000,
    attendanceRate: 92,
    newStudentsThisMonth: 86,
    pendingPayments: 14,
};

export const revenueSeries = [
    { month: "Yan", revenue: 142, target: 150 },
    { month: "Fev", revenue: 158, target: 155 },
    { month: "Mar", revenue: 171, target: 165 },
    { month: "Apr", revenue: 164, target: 170 },
    { month: "May", revenue: 182, target: 175 },
    { month: "Iyn", revenue: 176, target: 180 },
    { month: "Iyl", revenue: 184, target: 185 },
    { month: "Avg", revenue: 178, target: 185 },
    { month: "Sen", revenue: 184, target: 190 },
];

export const attendanceSeries = [
    { day: "Dush", present: 92, absent: 8 },
    { day: "Sesh", present: 88, absent: 12 },
    { day: "Chor", present: 95, absent: 5 },
    { day: "Pay", present: 90, absent: 10 },
    { day: "Jum", present: 86, absent: 14 },
    { day: "Shan", present: 78, absent: 22 },
];

export const courseDistribution = [
    { name: "Frontend", value: 32, color: "hsl(222 68% 28%)" },
    { name: "Backend", value: 24, color: "hsl(199 76% 56%)" },
    { name: "Mobile", value: 18, color: "hsl(152 56% 40%)" },
    { name: "Dizayn", value: 14, color: "hsl(38 92% 56%)" },
    { name: "Boshqalar", value: 12, color: "hsl(262 52% 56%)" },
];

export const students = [
    {
        id: 1,
        firstName: "Akmal",
        lastName: "Karimov",
        phone: "+998901234567",
        email: "akmal@mail.com",
        group: "Frontend-N10",
        balance: 450000,
        status: "ACTIVE",
        joinedAt: "2026-07-12",
    },
    {
        id: 2,
        firstName: "Dilnoza",
        lastName: "Saidova",
        phone: "+998907654321",
        email: "dilnoza@mail.com",
        group: "Backend-N5",
        balance: 0,
        status: "ACTIVE",
        joinedAt: "2026-06-03",
    },
    {
        id: 3,
        firstName: "Jasur",
        lastName: "Toshmatov",
        phone: "+998911223344",
        email: "jasur@mail.com",
        group: "Mobile-N3",
        balance: 1200000,
        status: "FREEZE",
        joinedAt: "2026-05-21",
    },
    {
        id: 4,
        firstName: "Madina",
        lastName: "Yuldasheva",
        phone: "+998933344556",
        email: "madina@mail.com",
        group: "Frontend-N10",
        balance: 0,
        status: "ACTIVE",
        joinedAt: "2026-08-01",
    },
    {
        id: 5,
        firstName: "Bekzod",
        lastName: "Aliyev",
        phone: "+998944556677",
        email: "bekzod@mail.com",
        group: "Dizayn-N2",
        balance: 780000,
        status: "ACTIVE",
        joinedAt: "2026-07-28",
    },
    {
        id: 6,
        firstName: "Nilufar",
        lastName: "Rahimova",
        phone: "+998955667788",
        email: "nilufar@mail.com",
        group: "Backend-N5",
        balance: 0,
        status: "GRADUATED",
        joinedAt: "2026-01-15",
    },
    {
        id: 7,
        firstName: "Sardor",
        lastName: "Umarov",
        phone: "+998966778899",
        email: "sardor@mail.com",
        group: "Mobile-N3",
        balance: 320000,
        status: "INACTIVE",
        joinedAt: "2026-04-09",
    },
    {
        id: 8,
        firstName: "Zarina",
        lastName: "Kholmatova",
        phone: "+998977889900",
        email: "zarina@mail.com",
        group: "Frontend-N11",
        balance: 0,
        status: "ACTIVE",
        joinedAt: "2026-08-19",
    },
];

export const teachers = [
    {
        id: 1,
        firstName: "Aziz",
        lastName: "Mahkamov",
        phone: "+998901112233",
        specialty: "Frontend (React)",
        salaryType: "PERCENTAGE",
        salaryAmount: 35,
        groups: 4,
        status: "ACTIVE",
        hiredAt: "2025-09-01",
    },
    {
        id: 2,
        firstName: "Kamola",
        lastName: "Nazarova",
        phone: "+998902223344",
        specialty: "Backend (Node.js)",
        salaryType: "HOURLY",
        salaryAmount: 80000,
        groups: 3,
        status: "ACTIVE",
        hiredAt: "2025-08-15",
    },
    {
        id: 3,
        firstName: "Rustam",
        lastName: "Ergashev",
        phone: "+998903334455",
        specialty: "Mobile (Flutter)",
        salaryType: "FIXED",
        salaryAmount: 12000000,
        groups: 2,
        status: "ACTIVE",
        hiredAt: "2026-01-10",
    },
    {
        id: 4,
        firstName: "Gulnora",
        lastName: "Sattorova",
        phone: "+998904445566",
        specialty: "UI/UX Dizayn",
        salaryType: "PERCENTAGE",
        salaryAmount: 30,
        groups: 2,
        status: "ACTIVE",
        hiredAt: "2025-11-20",
    },
    {
        id: 5,
        firstName: "Davron",
        lastName: "Yusupov",
        phone: "+998905556677",
        specialty: "Frontend (Vue)",
        salaryType: "HOURLY",
        salaryAmount: 75000,
        groups: 1,
        status: "INACTIVE",
        hiredAt: "2025-06-05",
    },
];

export const courses = [
    {
        id: 1,
        name: "Frontend Development",
        price: 2500000,
        durationMonth: 6,
        durationHours: 3,
        status: "ACTIVE",
        students: 412,
    },
    {
        id: 2,
        name: "Backend (Node.js)",
        price: 2800000,
        durationMonth: 7,
        durationHours: 3,
        status: "ACTIVE",
        students: 308,
    },
    {
        id: 3,
        name: "Mobile (Flutter)",
        price: 3000000,
        durationMonth: 8,
        durationHours: 3,
        status: "ACTIVE",
        students: 231,
    },
    {
        id: 4,
        name: "UI/UX Dizayn",
        price: 2200000,
        durationMonth: 5,
        durationHours: 2,
        status: "ACTIVE",
        students: 179,
    },
    {
        id: 5,
        name: "DevOps",
        price: 3500000,
        durationMonth: 6,
        durationHours: 3,
        status: "INACTIVE",
        students: 96,
    },
    {
        id: 6,
        name: "Python Data Science",
        price: 3200000,
        durationMonth: 9,
        durationHours: 3,
        status: "ACTIVE",
        students: 154,
    },
];

export const groups = [
    {
        id: 1,
        name: "Frontend-N10",
        course: "Frontend Development",
        teacher: "Aziz Mahkamov",
        students: 18,
        maxStudent: 20,
        status: "ACTIVE",
        startDate: "2026-07-01",
    },
    {
        id: 2,
        name: "Frontend-N11",
        course: "Frontend Development",
        teacher: "Aziz Mahkamov",
        students: 16,
        maxStudent: 20,
        status: "ACTIVE",
        startDate: "2026-08-01",
    },
    {
        id: 3,
        name: "Backend-N5",
        course: "Backend (Node.js)",
        teacher: "Kamola Nazarova",
        students: 20,
        maxStudent: 20,
        status: "ACTIVE",
        startDate: "2026-06-01",
    },
    {
        id: 4,
        name: "Mobile-N3",
        course: "Mobile (Flutter)",
        teacher: "Rustam Ergashev",
        students: 12,
        maxStudent: 15,
        status: "ACTIVE",
        startDate: "2026-05-15",
    },
    {
        id: 5,
        name: "Dizayn-N2",
        course: "UI/UX Dizayn",
        teacher: "Gulnora Sattorova",
        students: 14,
        maxStudent: 16,
        status: "ACTIVE",
        startDate: "2026-07-28",
    },
    {
        id: 6,
        name: "DevOps-N1",
        course: "DevOps",
        teacher: "—",
        students: 0,
        maxStudent: 18,
        status: "PLANNED",
        startDate: "2026-10-01",
    },
];

export const payments = [
    {
        id: 1,
        student: "Akmal Karimov",
        group: "Frontend-N10",
        amount: 2500000,
        method: "CARD",
        status: "PAID",
        date: "2026-09-01",
    },
    {
        id: 2,
        student: "Dilnoza Saidova",
        group: "Backend-N5",
        amount: 2800000,
        method: "TRANSFER",
        status: "PAID",
        date: "2026-09-02",
    },
    {
        id: 3,
        student: "Jasur Toshmatov",
        group: "Mobile-N3",
        amount: 3000000,
        method: "CASH",
        status: "PENDING",
        date: "2026-09-03",
    },
    {
        id: 4,
        student: "Madina Yuldasheva",
        group: "Frontend-N10",
        amount: 2500000,
        method: "CARD",
        status: "PAID",
        date: "2026-09-04",
    },
    {
        id: 5,
        student: "Bekzod Aliyev",
        group: "Dizayn-N2",
        amount: 2200000,
        method: "CASH",
        status: "PENDING",
        date: "2026-09-05",
    },
    {
        id: 6,
        student: "Sardor Umarov",
        group: "Mobile-N3",
        amount: 1500000,
        method: "CARD",
        status: "REFUNDED",
        date: "2026-08-28",
    },
];

// Teacher dashboard data
export const teacherGroups = [
    {
        id: 1,
        name: "Frontend-N10",
        course: "Frontend Development",
        students: 18,
        schedule: "Dush, Chor, Jum 14:00-16:00",
        room: "Xona-A2",
        nextLesson: "React Hooks",
    },
    {
        id: 2,
        name: "Frontend-N11",
        course: "Frontend Development",
        students: 16,
        schedule: "Sesh, Pay, Shan 10:00-12:00",
        room: "Xona-B1",
        nextLesson: "JS Asoslari",
    },
];

export const teacherLessons = [
    {
        id: 1,
        group: "Frontend-N10",
        title: "React Hooks",
        date: "2026-09-10",
        time: "14:00",
        status: "SCHEDULED",
        attendance: 17,
    },
    {
        id: 2,
        title: "Context API",
        group: "Frontend-N10",
        date: "2026-09-08",
        time: "14:00",
        status: "DONE",
        attendance: 18,
    },
    {
        id: 3,
        title: "useEffect chuqur",
        group: "Frontend-N10",
        date: "2026-09-05",
        time: "14:00",
        status: "DONE",
        attendance: 16,
    },
    {
        id: 4,
        title: "JS Asoslari",
        group: "Frontend-N11",
        date: "2026-09-09",
        time: "10:00",
        status: "SCHEDULED",
        attendance: null,
    },
];

export const homeworkToCheck = [
    {
        id: 1,
        student: "Akmal Karimov",
        group: "Frontend-N10",
        title: "Todo App",
        submittedAt: "2026-09-09",
        status: "PENDING",
    },
    {
        id: 2,
        student: "Madina Yuldasheva",
        group: "Frontend-N10",
        title: "Form Validation",
        submittedAt: "2026-09-08",
        status: "NEEDS_REVISION",
    },
    {
        id: 3,
        student: "Zarina Kholmatova",
        group: "Frontend-N11",
        title: "Flexbox layout",
        submittedAt: "2026-09-07",
        status: "PENDING",
    },
];

// Student dashboard data
export const studentInfo = {
    firstName: "Akmal",
    lastName: "Karimov",
    group: "Frontend-N10",
    course: "Frontend Development",
    teacher: "Aziz Mahkamov",
    balance: 450000,
    attendance: 94,
    progress: 62,
};

export const studentSchedule = [
    {
        id: 1,
        day: "Dush",
        title: "React Hooks",
        time: "14:00 - 16:00",
        room: "Xona-A2",
        status: "SCHEDULED",
    },
    {
        id: 2,
        day: "Chor",
        title: "Context API",
        time: "14:00 - 16:00",
        room: "Xona-A2",
        status: "SCHEDULED",
    },
    {
        id: 3,
        day: "Jum",
        title: "React Router",
        time: "14:00 - 16:00",
        room: "Xona-A2",
        status: "SCHEDULED",
    },
];

export const studentHomework = [
    {
        id: 1,
        title: "Todo App",
        deadline: "2026-09-12",
        status: "PENDING",
        grade: null,
    },
    {
        id: 2,
        title: "Form Validation",
        deadline: "2026-09-09",
        status: "ACCEPTED",
        grade: 5,
    },
    {
        id: 3,
        title: "Flexbox layout",
        deadline: "2026-09-05",
        status: "ACCEPTED",
        grade: 4,
    },
    {
        id: 4,
        title: "CSS Grid",
        deadline: "2026-09-02",
        status: "REJECTED",
        grade: 2,
    },
];

export const studentPayments = [
    {
        id: 1,
        amount: 2500000,
        method: "CARD",
        status: "PAID",
        date: "2026-09-01",
        period: "Sentabr",
    },
    {
        id: 2,
        amount: 2500000,
        method: "CARD",
        status: "PAID",
        date: "2026-08-01",
        period: "Avgust",
    },
    {
        id: 3,
        amount: 2500000,
        method: "CASH",
        status: "PAID",
        date: "2026-07-01",
        period: "Iyul",
    },
];

export const formatMoney = (n) =>
    new Intl.NumberFormat("ru-RU").format(n) + " so'm";

// ===== Yangi sahifalar uchun mock ma'lumotlar =====

export const rooms = [
    {
        id: 1,
        name: "Xona-A1",
        capacity: 24,
        occupied: 20,
        status: "OCCUPIED",
        type: "Kompyuter xonasi",
    },
    {
        id: 2,
        name: "Xona-A2",
        capacity: 20,
        occupied: 18,
        status: "OCCUPIED",
        type: "Kompyuter xonasi",
    },
    {
        id: 3,
        name: "Xona-B1",
        capacity: 16,
        occupied: 16,
        status: "OCCUPIED",
        type: "Oddiy sinf",
    },
    {
        id: 4,
        name: "Xona-B2",
        capacity: 16,
        occupied: 9,
        status: "FREE",
        type: "Oddiy sinf",
    },
    {
        id: 5,
        name: "Xona-C1",
        capacity: 30,
        occupied: 24,
        status: "OCCUPIED",
        type: "Ma'ruza zali",
    },
    {
        id: 6,
        name: "Xona-C2",
        capacity: 12,
        occupied: 0,
        status: "MAINTENANCE",
        type: "Laboratoriya",
    },
];

export const notifications = [
    {
        id: 1,
        type: "PAYMENT",
        title: "Yangi to'lov qabul qilindi",
        text: "Dilnoza Saidova Backend-N5 guruhiga 2 800 000 so'm to'lov qildi.",
        time: "10 daqiqa oldin",
        unread: true,
    },
    {
        id: 2,
        type: "LESSON",
        title: "Dars vaqti o'zgartirildi",
        text: "Frontend-N10 guruhining Juma kungi darsi 16:00 ga ko'chirildi.",
        time: "1 soat oldin",
        unread: true,
    },
    {
        id: 3,
        type: "HOMEWORK",
        title: "Uy vazifasi topshirildi",
        text: "Zarina Kholmatova 'Flexbox layout' vazifasini topshirdi.",
        time: "3 soat oldin",
        unread: true,
    },
    {
        id: 4,
        type: "SYSTEM",
        title: "Yangi talaba ro'yxatdan o'tdi",
        text: "Madina Yuldasheva Frontend-N11 guruhiga qo'shildi.",
        time: "Kecha, 18:42",
        unread: false,
    },
    {
        id: 5,
        type: "PAYMENT",
        title: "To'lov eslatmasi",
        text: "Jasur Toshmatovning 3 000 000 so'm to'lovi kutilmoqda.",
        time: "Kecha, 12:10",
        unread: false,
    },
    {
        id: 6,
        type: "SYSTEM",
        title: "Tizim yangilanishi",
        text: "Learnix 2.4 versiyasi o'rnatildi — davomat moduli yaxshilandi.",
        time: "2 kun oldin",
        unread: false,
    },
];

export const libraryResources = [
    {
        id: 1,
        title: "JavaScript: The Definitive Guide",
        type: "BOOK",
        category: "Dasturlash",
        author: "David Flanagan",
        size: "12.4 MB",
        downloads: 320,
    },
    {
        id: 2,
        title: "React Hooks — video kurs",
        type: "VIDEO",
        category: "Dasturlash",
        author: "Aziz Mahkamov",
        size: "1.2 GB",
        downloads: 189,
    },
    {
        id: 3,
        title: "UI/UX Dizayn asoslari",
        type: "PDF",
        category: "Dizayn",
        author: "Gulnora Sattorova",
        size: "8.1 MB",
        downloads: 142,
    },
    {
        id: 4,
        title: "Node.js va Express — prezentatsiya",
        type: "PRESENTATION",
        category: "Dasturlash",
        author: "Kamola Nazarova",
        size: "5.6 MB",
        downloads: 98,
    },
    {
        id: 5,
        title: "Technical English",
        type: "BOOK",
        category: "Ingliz tili",
        author: "O. Karimova",
        size: "15.2 MB",
        downloads: 264,
    },
    {
        id: 6,
        title: "Chiziqli algebra — ma'ruza qo'llanmasi",
        type: "PDF",
        category: "Matematika",
        author: "R. Ergashev",
        size: "6.3 MB",
        downloads: 77,
    },
    {
        id: 7,
        title: "Discret matematika videoto'plami",
        type: "VIDEO",
        category: "Matematika",
        author: "N. Yusupov",
        size: "840 MB",
        downloads: 51,
    },
    {
        id: 8,
        title: "Figma bo'yicha amaliy qo'llanma",
        type: "PRESENTATION",
        category: "Dizayn",
        author: "M. Xolmatova",
        size: "4.2 MB",
        downloads: 113,
    },
];

export const exams = [
    {
        id: 1,
        name: "React intermediat nazorat",
        group: "Frontend-N10",
        date: "2026-09-05",
        avgScore: 4.4,
        participants: 18,
        passRate: 89,
        status: "COMPLETED",
    },
    {
        id: 2,
        name: "JS Asoslari — 1-modul",
        group: "Frontend-N11",
        date: "2026-09-18",
        avgScore: null,
        participants: 16,
        passRate: null,
        status: "SCHEDULED",
    },
    {
        id: 3,
        name: "Node.js Express test",
        group: "Backend-N5",
        date: "2026-09-01",
        avgScore: 4.1,
        participants: 20,
        passRate: 85,
        status: "COMPLETED",
    },
    {
        id: 4,
        name: "Flutter widgets nazorati",
        group: "Mobile-N3",
        date: "2026-09-25",
        avgScore: null,
        participants: 12,
        passRate: null,
        status: "SCHEDULED",
    },
];

export const examResults = [
    {
        id: 1,
        student: "Akmal Karimov",
        score: 92,
        grade: 5,
        status: "ACCEPTED",
    },
    {
        id: 2,
        student: "Madina Yuldasheva",
        score: 84,
        grade: 4,
        status: "ACCEPTED",
    },
    {
        id: 3,
        student: "Sardor Umarov",
        score: 75,
        grade: 4,
        status: "ACCEPTED",
    },
    {
        id: 4,
        student: "Zarina Kholmatova",
        score: 61,
        grade: 3,
        status: "NEEDS_REVISION",
    },
    {
        id: 5,
        student: "Bekzod Aliyev",
        score: 48,
        grade: 2,
        status: "REJECTED",
    },
];

export const reportSeries = [
    { month: "Yan", revenue: 1420, expenses: 980, profit: 440 },
    { month: "Fev", revenue: 1580, expenses: 1010, profit: 570 },
    { month: "Mar", revenue: 1710, expenses: 1040, profit: 670 },
    { month: "Apr", revenue: 1640, expenses: 1090, profit: 550 },
    { month: "May", revenue: 1820, expenses: 1120, profit: 700 },
    { month: "Iyn", revenue: 1760, expenses: 1080, profit: 680 },
    { month: "Iyl", revenue: 1840, expenses: 1150, profit: 690 },
    { month: "Avg", revenue: 1780, expenses: 1100, profit: 680 },
    { month: "Sen", revenue: 1840, expenses: 1130, profit: 710 },
];

export const groupAttendance = [
    { group: "Frontend-N10", rate: 94 },
    { group: "Frontend-N11", rate: 91 },
    { group: "Backend-N5", rate: 88 },
    { group: "Mobile-N3", rate: 86 },
    { group: "Dizayn-N2", rate: 96 },
];

export const courseReports = [
    {
        course: "Frontend Development",
        students: 412,
        revenue: 820,
        attendance: 93,
        rating: 4.8,
    },
    {
        course: "Backend (Node.js)",
        students: 308,
        revenue: 710,
        attendance: 89,
        rating: 4.6,
    },
    {
        course: "Mobile (Flutter)",
        students: 231,
        revenue: 590,
        attendance: 87,
        rating: 4.5,
    },
    {
        course: "UI/UX Dizayn",
        students: 179,
        revenue: 380,
        attendance: 95,
        rating: 4.9,
    },
    {
        course: "Python Data Science",
        students: 154,
        revenue: 420,
        attendance: 91,
        rating: 4.7,
    },
];

export const faqs = [
    {
        category: "Umumiy",
        q: "Learnix'da qanday rollar mavjud?",
        a: "Tizimda uch xil rol mavjud: Admin (markazni to'liq boshqaradi), O'qituvchi (guruhlar, darslar va davomat) va Talaba (dars jadvali, vazifalar, to'lovlar).",
    },
    {
        category: "Umumiy",
        q: "Profil ma'lumotlarimni qanday o'zgartiraman?",
        a: "Profil sahifasiga o'tib, 'Shaxsiy ma'lumotlar' yorlig'ida ism, email va telefon raqamingizni yangilab, 'Saqlash' tugmasini bosing.",
    },
    {
        category: "Hisob",
        q: "Parolimni unutdim, nima qilishim kerak?",
        a: "Login sahifasidagi 'Parolni unutdingiz?' havolasini bosing — emailga parolni tiklash havolasi yuboriladi.",
    },
    {
        category: "Hisob",
        q: "Parolni qanday yangilayman?",
        a: "Profil → 'Parolni yangilash' bo'limiga o'tib, joriy parolni kiriting va yangi parolni ikki marta tasdiqlang (kamida 6 belgi).",
    },
    {
        category: "To'lovlar",
        q: "To'lovni qanday amalga oshiraman?",
        a: "To'lovlar sahifasida karta, naqd yoki o'tkazma orqali to'lash mumkin. To'lovlar tarixi shu yerda ko'rsatiladi.",
    },
    {
        category: "To'lovlar",
        q: "Balansim qarzli bo'lsa nima bo'ladi?",
        a: "Balans qarzli bo'lganda sizga eslatma bildirishnomalari yuboriladi. Uzoq muddatli qarzda hisob muzlatilishi mumkin.",
    },
    {
        category: "Darslar",
        q: "Dars jadvali qayerda ko'rinadi?",
        a: "Talabalar uchun 'Dars jadvali' sahifasida haftalik jadval, xona va vaqt ko'rsatiladi. Dars o'zgarsha bildirishnoma keladi.",
    },
    {
        category: "Darslar",
        q: "Darsga kelmadim, davomatga ta'sir qiladimi?",
        a: "Ha, har bir darsdagi davomat o'qituvchi tomonidan belgilanadi va umumiy davomat foizingizga kiritiladi.",
    },
];
